/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        lightBlue: 'var(--ns-light-blue)',
        netskopeBlue: 'var(--ns-netskope-blue)',
        deepBlue: 'var(--ns-deep-blue)',
        teal: 'var(--ns-teal)',
        lightningGreen: 'var(--ns-lightning-green)',
        orange: 'var(--ns-orange)',
        monoWhite: 'var(--ns-mono-white)',
        netskopeGray: 'var(--ns-netskope-gray)',
        ink: {
          900: 'var(--ns-ink-900)',
          800: 'var(--ns-ink-800)',
          700: 'var(--ns-ink-700)',
          600: 'var(--ns-ink-600)',
          500: 'var(--ns-ink-500)',
          400: 'var(--ns-ink-400)',
          300: 'var(--ns-ink-300)',
          200: 'var(--ns-ink-200)',
          100: 'var(--ns-ink-100)',
          50: 'var(--ns-ink-050)',
        },
        bg: {
          DEFAULT: 'var(--ns-bg)',
          alt: 'var(--ns-bg-alt)',
          tint: 'var(--ns-bg-tint)',
          inverse: 'var(--ns-bg-inverse)',
        },
        fg: {
          1: 'var(--ns-fg-1)',
          2: 'var(--ns-fg-2)',
          3: 'var(--ns-fg-3)',
          onDark1: 'var(--ns-fg-on-dark-1)',
          onDark2: 'var(--ns-fg-on-dark-2)',
        },
        border: 'var(--ns-border)',
        borderStrong: 'var(--ns-border-strong)',
        divider: 'var(--ns-divider)',
        link: 'var(--ns-link)',
        linkHover: 'var(--ns-link-hover)',
        success: 'var(--ns-success)',
        warning: 'var(--ns-warning)',
        danger: 'var(--ns-danger)',
        info: 'var(--ns-info)',
      },
      fontFamily: {
        sans: 'var(--ns-font-sans)',
        serif: 'var(--ns-font-serif)',
        mono: 'var(--ns-font-mono)',
      },
      fontSize: {
        'display-xl': 'var(--ns-fs-display-xl)',
        'display-lg': 'var(--ns-fs-display-lg)',
        'display-md': 'var(--ns-fs-display-md)',
        'h1': 'var(--ns-fs-h1)',
        'h2': 'var(--ns-fs-h2)',
        'h3': 'var(--ns-fs-h3)',
        'h4': 'var(--ns-fs-h4)',
        'body-lg': 'var(--ns-fs-body-lg)',
        'body': 'var(--ns-fs-body)',
        'body-sm': 'var(--ns-fs-body-sm)',
        'eyebrow': 'var(--ns-fs-eyebrow)',
        'caption': 'var(--ns-fs-caption)',
      },
      lineHeight: {
        tight: 'var(--ns-lh-tight)',
        display: 'var(--ns-lh-display)',
        snug: 'var(--ns-lh-snug)',
        normal: 'var(--ns-lh-normal)',
        relaxed: 'var(--ns-lh-relaxed)',
      },
      letterSpacing: {
        display: 'var(--ns-tracking-display)',
        tight: 'var(--ns-tracking-tight)',
        normal: 'var(--ns-tracking-normal)',
        eyebrow: 'var(--ns-tracking-eyebrow)',
      },
      spacing: {
        s1: 'var(--ns-s-1)',
        s2: 'var(--ns-s-2)',
        s3: 'var(--ns-s-3)',
        s4: 'var(--ns-s-4)',
        s5: 'var(--ns-s-5)',
        s6: 'var(--ns-s-6)',
        s7: 'var(--ns-s-7)',
        s8: 'var(--ns-s-8)',
        s9: 'var(--ns-s-9)',
      },
      borderRadius: {
        sm: 'var(--ns-r-sm)',
        md: 'var(--ns-r-md)',
        lg: 'var(--ns-r-lg)',
        xl: 'var(--ns-r-xl)',
        photo: 'var(--ns-r-photo)',
        pill: 'var(--ns-r-pill)',
      },
      boxShadow: {
        1: 'var(--ns-shadow-1)',
        2: 'var(--ns-shadow-2)',
        3: 'var(--ns-shadow-3)',
        'glow-cyan': 'var(--ns-shadow-glow-cyan)',
      },
      transitionTimingFunction: {
        standard: 'var(--ns-ease-standard)',
        emphasized: 'var(--ns-ease-emphasized)',
      },
      transitionDuration: {
        fast: 'var(--ns-dur-fast)',
        base: 'var(--ns-dur-base)',
        slow: 'var(--ns-dur-slow)',
      },
      fontWeight: {
        regular: 'var(--ns-fw-regular)',
        medium: 'var(--ns-fw-medium)',
        semibold: 'var(--ns-fw-semibold)',
      },
    },
  },
  plugins: [],
}
